version: '3.8'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    networks:
      - full-stack_chatapp_full-stack

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: full-stack_backend
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    networks:
      - full-stack_chatapp_full-stack

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: full-stack_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - full-stack_chatapp_full-stack

networks:
  full-stack_chatapp_full-stack:
    driver: bridge

volumes:
  mongo-data:

