apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: chat-app
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None  # Headless Service for stable DNS
  selector:
    app: mysql

